Some improvements and bug fixes
mxcube/HardwareRepository pull request #586
Opened 2020-09-14 07:04 UTC by marcus-oscarsson

Dear all,

A few fixes we have made the last weeks, since the last PR, it mainly contains a few fixes to the 
ESRF specific parts but also some general improvements. There is also the re_emit_values fix
for AbstractNState that was discussed during last developers meeting and which caused @vrey01 
and @jan-meyer some issues.

All the best,
Marcus

2020-09-14 07:17 UTC, IvarsKarpics approved these changes

2020-09-14 15:14 UTC, rhfogh commented on HardwareObjects/ESRF/BeamCmds.py
> +        cmd = getattr(self._hwobj, "set_value")(value, timeout=None)
Are you sure this works?
It looks (to me) like it should evaluate to

cmd = self._hwobj.set_value(value, timeout=None) # which should return None

So the next line would evaluat to 

self._cmd_execution = gevent.spawn(None)

Or have I missed something?

2020-09-14 15:16 UTC, rhfogh commented on HardwareObjects/ESRF/BeamCmds.py
> +                res = getattr(self._hwobj, "get_value")(timeout=None).name.lower()
If self._hwobj is a hwobj this ought to be the same as

self._hwobj.get_value(timepout=None).name.lower()

So what is actually happening here?

2020-09-14 15:16 UTC, rhfogh commented on HardwareObjects/ESRF/BeamCmds.py
> +            value = getattr(self._hwobj, "get_value")()
Like previous comments

2020-09-14 15:18 UTC, rhfogh commented on HardwareObjects/ESRF/Transmission.py
> +        # Busy is set by Abstractactuator, simply set state to ready
AbstractActuator (A not a)

2020-09-14 15:22 UTC, rhfogh commented on HardwareObjects/FlexHCDMaintenance.py
> +            self._do_change_gripper(int(args))
args (plural!) would normally be assumed to be a list. Is it a string? And how do we know it is convertible to int?

2020-09-14 15:26 UTC, rhfogh commented on HardwareObjects/XMLRPCServer.py
> +    def shape_history_get_grid(self, sid):
Documentaiont for 'sid' parameter?

2020-09-14 15:35 UTC, rhfogh requested changes

2020-09-14 15:35 UTC, rhfogh commented on HardwareObjects/abstract/AbstractActuator.py
> -            self.update_state(self.STATES.BUSY)
This needs consderation. Which function and class is responsible for setting state to BUSY, and where is it documented - if we canot assume that the abstract classes are correct? I think this change will (partially) break ActuatorMockup - in that class _set_value sets state to READY at the end, but nothing ever sets state to BUSY.

No objection to having the state setting done in _set_value if you think that is better for some reason (maybe that is what we did or should have done all along) but I think we need to have it clear what must happen where.

2020-09-15 06:02 UTC, marcus-oscarsson commented on HardwareObjects/abstract/AbstractActuator.py
> -            self.update_state(self.STATES.BUSY)
Hm, I believe was me who added this line in my last PR due to a delay in certain events for diffractometer motors. The event were delayed and the movement short so that the motor finished moving before the busy event arrived. We then realized that it was better to not have this here so we remove this line.

2020-09-15 06:04 UTC, marcus-oscarsson commented on HardwareObjects/XMLRPCServer.py
> +    def shape_history_get_grid(self, sid):
Its shape id, sid for short, sorry I did not add a documentation this time

2020-09-15 06:06 UTC, marcus-oscarsson commented on HardwareObjects/FlexHCDMaintenance.py
> +            self._do_change_gripper(int(args))
We know that its convertible to int because gripper in the context of the FlexHCD is passed as a string and in this case args is a single string.The code was written like this and it was simply addition to be able to handle several different grippers. I'm sure it can be improved.

2020-09-15 06:21 UTC, marcus-oscarsson commented on HardwareObjects/ESRF/BeamCmds.py
> +        cmd = getattr(self._hwobj, "set_value")(value, timeout=None)
Hm, I think this is a git mishap Ill take a closer look too see what happened :)

2020-09-15 09:11 UTC, rhfogh commented on HardwareObjects/abstract/AbstractActuator.py
> -            self.update_state(self.STATES.BUSY)
OK. 

Can we sum it up by saying that for real motors the state is set by the hardware? While for mokcups the mockup implementation must set BUSY?

2020-09-15 09:12 UTC, rhfogh commented on HardwareObjects/FlexHCDMaintenance.py
> +            self._do_change_gripper(int(args))
It is basically a naming issue. If you haven avariable called 'args' you take it for granted that it is a list - and you likely code on that assumption. Better to have name and use consistent.

2020-09-16 06:11 UTC, marcus-oscarsson commented on HardwareObjects/ESRF/BeamCmds.py
> +        cmd = getattr(self._hwobj, "set_value")(value, timeout=None)
So, we managed to fix this little problem when merging our different pieces of code. The BeamCmds object will likely be reworked a bit more soon but this is whats used today

2020-09-16 06:26 UTC, marcus-oscarsson commented on HardwareObjects/abstract/AbstractActuator.py
> -            self.update_state(self.STATES.BUSY)
Sure any "soft" motor would need to call `self.update_state(self.STATES.BUSY)` in someway and I guess it in most cases dont hurt to have it in implementation on top of real hardware. That hardware would/should in anyways handle the READY state

I'd be happy to put it back in again, but I wanted to remove it as it was me who added it and it was to resolve a issue we had a with a specific motor that I though was general enough to be in AbstractActuator. I than had another think about thought it was better to remove this logic from AbstractActuator and push it down to in this case ExporterMotor and perhaps move it up to AbstractMotor if it turns out to be a general problem.

But its otherwise fine as it is now

2020-09-16 06:29 UTC, marcus-oscarsson commented on HardwareObjects/FlexHCDMaintenance.py
> +            self._do_change_gripper(int(args))
Sure I agree with your argument on the naming, we could maybe leave as it is right now and ill have a look at this part of the code at a later time. If thats not too painful for your eyes ...

2020-09-16 06:32 UTC, marcus-oscarsson commented
Okey we fixed our little git mishap and also added a few more fixes.

@rhfogh I'am sorry for the variable naming, we simply did what we needed to add a function to some existing code so I think it would be good if could that one go for the moment until we have another look at that code in general.

2020-09-16 08:31 UTC, rhfogh commented on HardwareObjects/ESRF/BeamCmds.py
> +        cmd = getattr(self._hwobj, "set_value")(value, timeout=None)
Cool.

For my own education, could you tell me what kind of object self._hwobj is? 'Cause if it is a HardwareObject I still think that cmd evaluates to None. The code could work even so, with the setting done in the 'cmd =' line and the spawned process being a no-op. If this is good enough for now that is fine with me, but I just want to make sure there is not something there that I have misunderstood

2020-09-16 08:34 UTC, rhfogh commented on HardwareObjects/abstract/AbstractActuator.py
> -            self.update_state(self.STATES.BUSY)
@marcus-oscarsson 
This makes sense. I think you are right in removing it and not putting it back.  I just was not sure which layer was responsible for setting BUSY an assumed that it was this function (since the code was there).

We just need to remember to go through the mock motors and make sure they set BUSY as they should.

2020-09-16 08:35 UTC, rhfogh commented on HardwareObjects/FlexHCDMaintenance.py
> +            self._do_change_gripper(int(args))
Cool. I care about the principle of it, but not that much about a small individual instance.

2020-09-16 09:25 UTC, marcus-oscarsson commented on HardwareObjects/ESRF/BeamCmds.py
> +        cmd = getattr(self._hwobj, "set_value")(value, timeout=None)
Well this code is now valid any longer but there is something similar in another place and in that case its actually a function

2020-09-21 09:25 UTC, rhfogh approved these changes
All issues sorted now.

2020-09-21 10:28 UTC, marcus-oscarsson commented
Okey so Ill merge then :)

2020-09-21 10:28 UTC, merged