LNLS site-specific config
mxcube/HardwareRepository pull request #608
Opened 2020-12-18 18:18 UTC by laispc

Hi,

This is a PR to share LNLS site-specific code (classes, config). Hopefully it will not affect general code (if it happens we can treat in separated PR maybe). This is the code we have been using for a while now (more recent code will come next).

There is still some fixes to do (squashes, code style), so I am putting this as a draft PR for now. But feel free to make comments and suggestions anytime, as the main purpose here is to share and receive critique on the work done. Thanks in advance! ;)

2020-12-18 18:33 UTC, IvarsKarpics requested changes

2020-12-18 18:33 UTC, IvarsKarpics commented on HardwareObjects/GenericDiffractometer.py
> +                self.move_to_motors_positions({}, wait=True)
Hmm, why this was removed?

2020-12-18 19:17 UTC, laispc commented on HardwareObjects/GenericDiffractometer.py
> +                self.move_to_motors_positions({}, wait=True)
@IvarsKarpics it was done just for a test, it was intended to be reverted and does not apply anymore, sorry.
I will drop this change, thanks!

2020-12-21 09:55 UTC, beteva commented on HardwareObjects/LNLS/LNLSInOut.py
> +import logging
@laispc, this code is just fine. Unfortunately with the new HardwareRepository structure we decided to drop the inheritance from Device and Equipment and only use HardwareObject. Moreover, for InOut, there is AbstractNState. If you want to use the new HardwareRepository structure, you may want to change this to LNLSNState, which inherits from AbstractNState. You could see ExporterNState as an example

2020-12-21 10:04 UTC, beteva commented on HardwareObjects/LNLS/LNLSMotor.py
> +        if None in limits:
The same code is in AbstractMotor, except for the casting of value to float. Do you really need it?

2020-12-21 10:12 UTC, beteva commented on HardwareObjects/LNLS/LNLSTransmission.py
> +        self.energy = self.getObjectByRole("energy")
you could use:
from HardwareRepository import HardwareRepository as HWR
and then self.energy could be replaced by HWR.beamline.energy
Thus the energy HO will only be defined in beamline_config.yml for any place you want to use the energy

2021-01-20 18:40 UTC, laispc commented on HardwareObjects/LNLS/LNLSTransmission.py
> +        self.energy = self.getObjectByRole("energy")
Great! It could make the code/config more simple indeed.

2021-01-20 18:43 UTC, laispc commented on HardwareObjects/LNLS/LNLSMotor.py
> +        if None in limits:
I remember duplicating this part due to a inheritance bug on this class, but I will check again if it's still necessary.

2021-01-20 18:44 UTC, laispc commented on HardwareObjects/LNLS/LNLSInOut.py
> +import logging
Thanks for the info! I will try to refactor this part.

2021-01-20 18:45 UTC, laispc commented
@beteva thanks for the review so far. I am working on them and testing.

@IvarsKarpics thank you too, I already applied the changes you recommended.

2021-01-22 10:14 UTC, IvarsKarpics requested changes
Apart from few comments and swp file in the commit, the PR looks fine.

2021-01-22 10:14 UTC, IvarsKarpics commented on configuration/lnls_manaca/detector_mockup.xml
> +<equipment class = "LNLS.LNLSPilatusDet">
maybe rename the config file to detector.xml?

2021-01-22 10:14 UTC, IvarsKarpics commented on configuration/lnls_manaca/ldapconnection.esrf.xml
> +<procedure class="LdapLogin">
?

2021-01-25 15:32 UTC, marcus-oscarsson commented on configuration/lnls_manaca/ldapconnection.esrf.xml
> +<procedure class="LdapLogin">
yes the .esrf. name is a bit funny :)

2021-01-25 15:35 UTC, marcus-oscarsson commented
Thanks for this really nice work @laispc :), @IvarsKarpics had a few final remarks that I think is worth having a look at.  I also think the PR is basically ready to be merged. Let us know when you are done with the last fixes :)

2021-01-25 16:22 UTC, laispc commented on configuration/lnls_manaca/ldapconnection.esrf.xml
> +<procedure class="LdapLogin">
Lol, I have borrowed the XML names from the mock config. I am renaming them. :) Thank you!

2021-02-05 21:53 UTC, laispc commented on HardwareObjects/LNLS/LNLSInOut.py
> +import logging
@beteva LNLSInOut refactored, now it is called EPICSNState, following the suggested structure.

2021-02-05 21:56 UTC, laispc commented on HardwareObjects/LNLS/LNLSMotor.py
> +        if None in limits:
I just removed this piece of code from LNLSMotor. It is not needed anymore. :)

Btw, LNLSMotor was renamed to EPICSMotor.

2021-02-05 21:56 UTC, laispc commented on Command/Epics.py
> +import Poller
Fixed.

2021-02-05 21:56 UTC, laispc commented on configuration/lnls_manaca/detector_mockup.xml
> +<equipment class = "LNLS.LNLSPilatusDet">
Fixed.

2021-02-05 21:57 UTC, laispc commented on configuration/lnls_manaca/ldapconnection.esrf.xml
> +<procedure class="LdapLogin">
All files renamed.

2021-02-05 21:58 UTC, laispc commented on Command/Epics.py
> +from CommandContainer import CommandObject, ChannelObject
Fixed.

2021-02-05 21:59 UTC, laispc commented on HardwareObjects/LNLS/LNLSTransmission.py
> +        self.energy = self.getObjectByRole("energy")
@beteva I just implemented you suggestion in LNLSTransmission and LNLSCollect. It worked fine, thanks!

2021-02-05 22:11 UTC, laispc commented
@beteva @IvarsKarpics @marcus-oscarsson , I just finished the suggested changes.
Feel free to take a look and make more suggestions if you want. Thank you! :)

2021-02-08 11:35 UTC, IvarsKarpics commented
Hi @laispc 

There is still one swap file in the commit. After removing it the PR is ready to be merged.

2021-02-08 19:01 UTC, laispc commented
> There is still one swap file in the commit. After removing it the PR is ready to be merged.

Hi @IvarsKarpics , shame on me, I removed the.swp from the PR, but I think it did not work in the end, sorry. 
I just fixed it and I think it is okay now. Thanks!

2021-02-09 08:20 UTC, IvarsKarpics approved these changes

2021-02-09 08:22 UTC, IvarsKarpics commented
Hi @laispc 

I see, now the swap file is gone. However I see that the travis is failing. Looks like there are few typos. Can you fix them so the travis is not failing?

2021-02-10 14:03 UTC, laispc commented
@IvarsKarpics yes, there was a typo in Command/Epics.py. Fixed!

Also, LNLS/test folder was being called by Travis by accident, as it has 'test' in the name. As it wasn't my intention to make LNLS/test be called by pytest yet, I am dropping LNLS/test from this PR because it is not critical. Travis is happy again. :)

However, this error it helped me to actually see the typo and that Command/Epics.py is not tested by Travis. As a future work we could try to add a test for Command/Epics.py. Does it make sense for HardwareRepository?

2021-02-10 14:11 UTC, IvarsKarpics commented
Hi @laispc 

Thanks for fixing the bug. Initially we where running pylint -E against all repository files, but at some point there was so many errors that we could not solve them easy. I think when we are ready with renaming of the repository we can check again why pylint is failing.
Also we can configure pytest so it is not running any other tests as those defined in the tests directory.

I am merging the PR.

2021-02-10 14:11 UTC, merged